version: '3.8'

services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8000:8000"
    networks:
      - runnerway

networks:
  runnerway:
    external: true
