serverhost: j11b304.p.ssafy.io
dbport: 3306
mysqlusername: root
mysqlpassword: 11b304@dlfcndlfcn
JWT: doeifnEo83nIRNSeinsorn39t0TN1NEOsncosn30cs8cs9dcsc7s8ERncsornewoirnd
redisport: 6379
redispassword: 11b304@dlfcndlfcn
swagger-url: /secret/swagger-of-chuchu/
elastic-user-name: elastic
elastic-password: 11b304@dlfcndlfcn